name: Run JavaScript Script

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜 12 點執行，使用 cron 表達式
  workflow_dispatch:  # 允許手動觸發工作流

jobs:
  run-script:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 作為運行環境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make test.js executable
        run: chmod +x test.js  # 設定檔案可執行

      - name: Run test.js script
        run: ./test.js  # 執行 test.js
